proxySettings:
  noProxy: true
  torProxy: false
  webProxy: false
browsers:
  chromium:
    enable: false
    key: "webdriver.chrome.driver"
    name: "chromedriver"
    options:
      headless: true
      logLevel: "off"
      pageLoadStrategy: "eager"
      pageLoadTimeout: 30
      implicitWaitTimeout: 30
      scriptTimeout: 30
      acceptInsecureCerts: true
  chrome:
    enable: true
    key: "webdriver.chrome.driver"
    name: "chromedriver"
    options:
      headless: true
      logLevel: "off"
      pageLoadStrategy: "eager"
      pageLoadTimeout: 30
      implicitWaitTimeout: 30
      scriptTimeout: 30
      acceptInsecureCerts: true
  firefox:
    enable: false
    key: "webdriver.gecko.driver"
    name: "geckodriver"
    options:
      headless: true
      logLevel: "fatal"
      pageLoadStrategy: "eager"
      pageLoadTimeout: 30
      implicitWaitTimeout: 30
      scriptTimeout: 30
      acceptInsecureCerts: true
  msedge:
    enable: false
    key: "webdriver.edge.driver"
    name: "msedgedriver"
    options:
      headless: true
      pageLoadStrategy: "eager"
      pageLoadTimeout: 30
      implicitWaitTimeout: 30
      scriptTimeout: 30
      acceptInsecureCerts: true
  opera:
    enable: false
    key: "webdriver.opera.driver"
    name: "operadriver"
    options:
      headless: true
      pageLoadStrategy: "eager"
      pageLoadTimeout: 30
      implicitWaitTimeout: 30
      scriptTimeout: 30
      acceptInsecureCerts: true