voteMode:
  voteCount: 1
  distanceCount: 2000
  threadEnabled: false
  threadCount: 1
  keepDistanceEnabled: true
  browsers:
    chromium:
      enable: false
    chrome:
      enable: true
    firefox:
      enable: false
    msedge:
      enable: false
    opera:
      enable: false